### ISSUE TITLE
Update redirector for Plone 5

### ISSUE THREAD

**Issue by paskyorg** [4teamwork/ftw.redirector#5]
It's possible update this addon for Plone 5? I would like use it. Thanks!

**Comment by jone** [comment]
`ftw.redirector` is not yet officially Plone 5 compatible.
We are currently updating our stack to Plone 5 and we will hopefully be able to update `ftw.redirector` in the next months.

**Comment by mbaechtold** [comment]
Support for Plone 5.1.x has been added in https://github.com/4teamwork/ftw.redirector/pull/7 (not yet released though).

**Comment by busykoala** [comment]
🗒 Please also add a profile for Plone 5.1.

**Comment by busykoala** [comment]
Further steps will be done in https://github.com/4teamwork/izug.organisation/issues/1399
